### PR TITLE
Adding border color, border width

### PR DESCRIPTION
**Pull request by sdgandhi**
@andreamazz I'm trying to add a border option to the pop tip, but looks like the `CALayer` is clipping. I tried the following without avail:
- Increase `bounds` of the the `CALayer`
- Disable `clipsToBounds` and `masksToBounds`

Any help on this would be awesome, thanks!

img_0057

### CODE REVIEW

**Comment by andreamazz** [comment]
Hi @sdgandhi 
It's a little trickier than that, checkout commit 9f23baf for a fix. It's only a partial fix, I only implemented the Down position. I'll implement the rest tomorrow, now I can't think straight :)

**Comment by sdgandhi** [comment]
@andreamazz Yeah, I worked on it unsuccessfully for a bit – I'm not super strong in CALayers. However, I believe we will need to draw the shape in a new CALayer where bounds are larger than the layer frame and add that as a sublayer to the main layer of the view.

**Comment by andreamazz** [comment]
Hi @sdgandhi 
In commit 1c67a76 you'll find the fix for the border. Let me know if everything is ok (please note that the default value for the border is now 0, so change your poptip's appearance accordingly).

**Comment by sdgandhi** [comment]
@andreamazz Great, thanks for looking at this so promptly.

**Pull request merged**
