### PR TITLE
Add constrainToView property to reposition tooltip in a specified view

### PR DESCRIPTION
**Pull request by jrabek**
Attempted fix for https://github.com/andreamazz/AMPopTip/issues/178

### CODE REVIEW

**Comment by jrabek** [comment]
Note that this isn't the perfect solution since the check for being constrained in a view should check both horizontally and vertically but I was trying to mimic the existing view constraint code.

As a side note, I noticed that `frame.origin.x - containerView.frame.origin.x` is subtracting x values from two different view coordinate spaces.  `frame` is based on `from` which is a frame in the coordinate space of `containerView` and `containerView.frame` is in the coordinate space of its superview.

**Comment by jrabek** [comment]
Also note that this shouldn't be merged as is.  Mostly to illustrate what I was referencing in the issue.

**Comment by andreamazz** [comment]
Hi @jrabek 
Thank you for your work, I'll look into it as soon as possible.

**Comment by jrabek** [comment]
No problem!  Note that I ended up doing it for a vertical tooltip to see if the concept makes sense before doing more.

**Pull request closed without merging**
