### PR TITLE
Adding bounce effect functionality to the popover

### PR DESCRIPTION
**Pull request by kevin-hirsch**
Hello @andreamazz,

I added this new bounce feature that I found cool too catch the user's attention on the popover.
Tell me what you think about it and if you can merge it I will be very happy! :smiley:

bounce_effect

### CODE REVIEW

**Comment by andreamazz** [comment]
That looks great. I'm tempted to add a whole series of animations (a jump like the icons in the OsX dock, or a pulsating effect) :)  
Thanks for the PR, merged. :+1:

**Comment by kevin-hirsch** [comment]
That's good ideas indeed! :)
Thanks to you!

**Comment by andreamazz** [comment]
Hi @kevin-hirsch 
I've added a couple of new animations and changed the API a bit. You animation is now called `AMPopTipActionAnimationFloat`.  
Animations are set like this:
```objc
    self.popTip.actionAnimation = AMPopTipActionAnimationBounce;
```

You find all this in the `develop` branch.

**Comment by kevin-hirsch** [comment]
Ah this rocks! :smiley: :+1:
In the same idea, don't forget my proposition on this issue:
"Different appearance animation / custom animation" #33
You could do the same but for the appearance animation ;)

Great work! Thanks a lot :)

**Comment by kevin-hirsch** [comment]
PS: Don't forget to change your README too ;)

**Pull request merged**
