### PR TITLE
Feature/animations

### PR DESCRIPTION
**Pull request by valeriomazzeo**
This pull request extend AMPopTip with the possibility of define an exit animation.
It also implements a new animation for fade in/out.

### CODE REVIEW

**Comment by Tbruni85** [comment]
Thanks @valeriomazzeo, about to do it as well!

:+1:

**Comment by Ricardo1980** [comment]
:+1:

**Comment by andreamazz** [comment]
Ciao @valeriomazzeo 
Thanks for the PR. I suggested some changes in the commit, if you'd be so kind to check them out I'll be happy to merge. :+1:

**Comment by valeriomazzeo** [comment]
@andreamazz done, please don't comment on the single commit, just do it on the `File Changes` tab

**Comment by valeriomazzeo** [comment]
@andreamazz are you alive?

**Comment by valeriomazzeo** [comment]
@andreamazz it would be great if you could bump the podspec version :)

**Comment by andreamazz** [comment]
0.10.2 should be live now.

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMPopTip/blob/master/CHANGELOG.md#0102

Cheers

**Comment by valeriomazzeo** [comment]
nice, thank you :+1:

**Comment by andreamazz** [comment]
:+1: 
Thanks for the PR. Sorry for the massive delay, I've been having trouble keeping up with my OS project lately.

**Pull request merged**
