### PR TITLE
Update for Swift 4.2 - Xcode 10

### PR DESCRIPTION
**Pull request by rgomesbr**
When converting a project to Swift 4.2, I had to locally change these lines on PopTip.swift for the conversion to work.

### CODE REVIEW

**Comment by robert-cronin** [comment]
Was about to make a PR :)
Hopefully we can get this resolved ASAP, there doesn't look to be anything too major, just syntax.

**Comment by andreamazz** [comment]
Cool, thanks, I'm making my annual pass on all my libraries to bump the swift version 😬

**Comment by rgomesbr** [comment]
@andreamazz, The new release, 3.5.0, worked just fine here, on Xcode 10 with Swift 4.2 :-) 
Thanks for releasing it.

**Comment by andreamazz** [comment]
Great. I was puzzled when merging this PR returned conflicts, then I realized that I made the changes myself yesterday. I need a vacation 😅

**Pull request merged**
